---
- hosts: all
  tasks:

    - name: Display node information
      debug:
        msg: "The node name OS: {{ ansible_nodename }}"

    - name: Display total memory
      debug:
        msg: "The total memory is: {{ ansible_memtotal_mb }} MB"

    - name: Display free memory
      debug:
        msg: "The free memory is: {{ ansible_memfree_mb }} MB"

    - name: Display number of processors (CPU cores)
      debug:
        msg: "The number of processors (CPU cores) is: {{ ansible_processor_cores }}"

    - name: Display OS family name
      debug:
        msg: "The name of OS family is: {{ ansible_os_family }}"

    - name: Display package manager
      debug:
        msg: "The package manager is: {{ ansible_pkg_mgr }}"
